services:
  api:
    build: .
    container_name: my-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MechiraSinit;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: my-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"